name: Deploy Website Baru
on:
  push:
    branches:
      - main # Pastikan branch utamamu namanya 'main' atau 'master'

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kodingan Terbaru
        uses: actions/checkout@v4

      - name: Kirim ke Hosting (FTP)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Kuncinya di sini:
          # Karena akun FTP-nya sudah diarahkan SPESIFIK ke folder baru,
          # Kita cukup pakai ./ saja.
          server-dir: ./
